// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Band = { id: string, name: string, 
/**
 * {instrument: memberName} のマップ
 */
members: { [key in string]?: string }, memberIds: Array<string>, createdAt: string, version: bigint, };
