// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackPriority } from "./FeedbackPriority";
import type { FeedbackStatus } from "./FeedbackStatus";
import type { FeedbackType } from "./FeedbackType";

export type Feedback = { id: string, userId: string, userName: string, type: FeedbackType, title: string, description: string, priority: FeedbackPriority, status: FeedbackStatus, createdAt: string, updatedAt: string | null, version: bigint, };
