// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Member = { id: string, name: string, grade: string, lineUserId: string | null, createdAt: string, version: bigint, };
