// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReservationStatus } from "./ReservationStatus";

export type Reservation = { id: string, userId: string, userName: string, bandId: string, bandName: string, roomId: string, roomName: string, timeSlotId: string, date: string, reservedAt: string, version: bigint, status: ReservationStatus, isPersonal: boolean, eventName: string | null, description: string | null, };
