// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimeSlot = { id: string, startTime: string, endTime: string, duration: number, displayName: string, };
